version: '3.8'

services:
  brouter:
    image: brouter-repository-compose-prod
    container_name: brouter-repository-compose-prod
    build:
      context: ./brouter-infra/brouter
      dockerfile: Dockerfile
    ports:
      - "17780:17777"
    volumes:
      - "./brouter-infra/maps:/segments4"
      - "./brouter-infra/profile:/profiles2"
    restart: unless-stopped
